version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8 

    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go version

